enyo.depends(
  "source/Contraption.js",
  "source/InitialSetup.js",
  "source/MainScreen.js",
  "source/PlayTimer.js",
  "source/RoundTimer.js",
  "source/HealthCounter.js",
  "css/Contraption.css"
);